- internal/format/format.go
- internal/modules/composer/commands.go
- internal/modules/composer/composerLockFile.go
- internal/modules/composer/handler.go
- internal/modules/composer/projectInfo.go
- internal/modules/composer/treeComponents.go
- internal/modules/modules.go
> feat(composer): update modules dependencies

- .github/workflows/release.yml
- Dockerfile
- README.md
* Adds docker file, docker release, and how to example
> Add Docker option

- README.md
- cmd/generator/generator.go
- internal/format/format.go
- internal/helper/helper.go
- internal/models/models.go
- internal/modules/gomod/decoder.go
- internal/modules/gomod/handler.go
- internal/modules/gomod/models.go
- Adds CheckSum process to auto calculate value based on content given
- Adds BuildManifestContent function to create a manifest from a directory tree
- *Completes SPDX output
*Missing values on Output
- 3.7  Package Download Location 
- 3.5  Package Supplier
> Completes SPDX output, and adds checksum calculation method

- internal/format/format.go
- internal/modules/gomod/commands.go
- internal/modules/gomod/decoder.go
- internal/modules/gomod/errors.go
- internal/modules/gomod/handler.go
- internal/modules/gomod/models.go
- Makes usage of `go list -deps` to get more accurate package usage
- Fixes a few SPDX file wrong output
> Changes core gomod commands to use  to get more accurate package usage

- internal/modules/javamaven/decoder.go
- internal/modules/javamaven/errors.go
- internal/modules/javamaven/handler.go
Few lint and pom.xml reading fix.
> Javemaven lint and other fixes

- internal/modules/npm/handler.go
- internal/modules/npm/handler_test.go
- internal/modules/yarn/handler.go
- internal/modules/yarn/handler_test.go
Bugs fixed:
- https://jira.linuxfoundation.org/browse/SSB-58
- https://jira.linuxfoundation.org/browse/SSB-60
- https://jira.linuxfoundation.org/browse/SSB-61
- https://jira.linuxfoundation.org/browse/SSB-62
- https://jira.linuxfoundation.org/browse/SSB-63
- https://jira.linuxfoundation.org/browse/SSB-64
- https://jira.linuxfoundation.org/browse/SSB-66
- https://jira.linuxfoundation.org/browse/SSB-68
> Fix npm and yarn bugs

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/docs_update.md
- .github/ISSUE_TEMPLATE/feature_request.md
- Added bug report, docs update, and new feature request issue templates
Signed-off-by: David Deal <dealako@gmail.com>
> Added New Issue Templates

- contributing.md
- Added contributing file which specifies Apache-2.0 license and DCO details.
Signed-off-by: David Deal <dealako@gmail.com>
> Added Contributing File

- internal/modules/nuget/handler.go
- internal/modules/nuget/helpers.go
Fixed the following issue - 
https://github.com/spdx/spdx-sbom-generator/issues/48
https://github.com/spdx/spdx-sbom-generator/issues/54
https://github.com/spdx/spdx-sbom-generator/issues/53
https://github.com/spdx/spdx-sbom-generator/issues/59
Few minor issues
> fixed the spdx warning issue and few minor issues

- internal/format/format.go
- internal/modules/pip/worker/decoder.go
In case the checksum generated happens to be NOASSERTION, we should not add it to spdx file generated for it to pass the spdx validation.
> Spdx remove checksum on noassertion

- internal/modules/gem/helper.go
Minor fix for windows environment
> windows support

- internal/modules/gem/helper.go
Adds checksum computation logic for windows use-cases
> windows checksum fix

- internal/modules/pip/worker/decoder.go
- internal/modules/pip/worker/pypi.go
> Python(Go) - Poetry - SPDX file validation failed in the SPDX validator issue fixed

- internal/modules/pip/pyenv/commands.go
- internal/modules/pip/pyenv/handler.go
> Python(Go) - venv - Not able to generate SPDX file issue fixed

- internal/modules/npm/handler.go
- internal/modules/yarn/handler.go
Fixes:
https://jira.linuxfoundation.org/browse/SSB-64
https://jira.linuxfoundation.org/browse/SSB-63
> fix dependency chain

- internal/modules/gem/helper.go
Bug Fixes :
NB : Some 3rd level dependencies do not have any manifest files (.gemspecs) existing in all the gem paths on localhost and so we have listed them as warning during the build process. This does not affect the final output spdx file except that they are not included as we have no meta-data to provide information about them.
https://github.com/spdx/spdx-sbom-generator/issues/135 
https://github.com/spdx/spdx-sbom-generator/issues/138
> github-135 and github-138 fixes

- internal/modules/npm/handler.go
- internal/modules/yarn/handler.go
- internal/modules/yarn/handler_test.go
Fixing: 
- https://github.com/spdx/spdx-sbom-generator/issues/83
- https://github.com/spdx/spdx-sbom-generator/issues/85
> Fix minor issues

- internal/format/format.go
- internal/models/models.go
- internal/modules/gomod/decoder.go
- Adds support to Supplier
- Adds support to PackageDownloadURL
- Will detect if main package is git based for GoMod only when building PackageDownloadURL
Validate new fields on:
> Adds Supplier and PackageDownloadURL support

- internal/modules/nuget/handler.go
- internal/modules/nuget/helpers.go
Signed-off-by: Prabodh Chaudhari <pchaudha@proximabiz.com>
fixed - https://github.com/spdx/spdx-sbom-generator/issues/48
> fixed the spdx file warning issue

- internal/format/format.go
- internal/models/models.go
- internal/modules/gomod/decoder.go
Enhanced module.Supplier.Get() to consume Email if it is already supplied to module.Supplier
> Enhancement to PackageSupplier in core module - Consume Email 

- internal/modules/nuget/handler.go
Fixed https://github.com/spdx/spdx-sbom-generator/issues/173
> Added the package download url

- internal/modules/npm/handler.go
- internal/modules/yarn/handler.go
Fixes: 
- https://github.com/spdx/spdx-sbom-generator/issues/187
> Update package supplier name

- internal/modules/nuget/handler.go
- internal/modules/nuget/helpers.go
Signed-off-by: Prabodh Chaudhari <pchaudha@proximabiz.com>
Fixed the below issues
https://github.com/spdx/spdx-sbom-generator/issues/173
https://github.com/spdx/spdx-sbom-generator/issues/188
> Fixed the root package download url issue

- internal/modules/gem/helper.go
scanned https://github.com/grpc/grpc , noticed a few bugs and fixed.
> minor fixes noticed after scanning against large gem repo

- internal/modules/pip/pipenv/handler.go
- internal/modules/pip/poetry/handler.go
- internal/modules/pip/pyenv/handler.go
- internal/modules/pip/worker/decoder.go
- internal/modules/pip/worker/metadata.go
- internal/modules/pip/worker/pypi.go
- internal/modules/pip/worker/worker.go
@niravpatel27
Package Supplier and Package Download Location support fixes and code cleanup
Issue Fixed #181
> Package Supplier and Package Download Location support fixes and code cleanup

- internal/modules/npm/handler.go
- internal/modules/yarn/handler.go
Fixes: 
- https://github.com/spdx/spdx-sbom-generator/issues/176
> Add support for PackageDownloadLocation

- internal/modules/npm/handler.go
- internal/modules/yarn/handler.go
> Fix get root package repository

- pkg/modules/javamaven/decoder.go
- pkg/modules/javamaven/handler.go
Signed-off-by: Appu Goundan <appu@google.com>
Fixes: https://github.com/spdx/spdx-sbom-generator/issues/206
Also use system provided temp directory.
> Pass working directory to maven command

- fuzzbuzz.yaml
- Added initial fuzzbuzz configuration file for testing/evaluating the fuzzer
Signed-off-by: David Deal <dealako@gmail.com>
> Added fuzzbuzz configuration file

- .github/workflows/release.yml
- Updates golang version for release GH Action to support `io.ReadAll` on the code
> Fixes broken release

- go.mod
- go.sum
- pkg/modules/javagradle/project_fuzz.go
- pkg/modules/javagradle/project_test.go
Signed-off-by: David Deal <dealako@gmail.com>
> Added Initial FuzzTests

- go.mod
- go.sum
- pkg/modules/javagradle/project_fuzz.go
- pkg/modules/javagradle/project_test.go
Reverts spdx/spdx-sbom-generator#221
> Revert "Added Initial FuzzTests"

- README.md
> Document Scoop installation method for Windows

- CONTRIBUTING.md
- README.md
Signed-off-by: Nisha Kumar <nisha.kumar@oracle.com>
> Add community weekly meeting times and link

- .github/workflows/build-pr.yml
- .github/workflows/merge-main.yml
The tests are failing due to some issue with running
npm install. In order to unblock PRs, we will disable
the tests for now.
Signed-off-by: Nisha Kumar <nisha.kumar@oracle.com>
> Disable tests for now

- CONTRIBUTING.md
Signed-off-by: Nisha Kumar <nisha.kumar@oracle.com>
> Add meeting minutes document to meeting info

- CONTRIBUTING.md
- README.md
- Added link to CONTRIBUTING to table of contents
- Updated community meeting time to 9am PST
Signed-off-by: Nisha Kumar <nisha.kumar@oracle.com>
> Update community particulars

- .github/workflows/build-pr.yml
- .github/workflows/merge-main.yml
- Makefile
- go.mod
Fixes https://github.com/opensbom-generator/spdx-sbom-generator/issues/298
> feat(ci): generate and validate SBOM
